/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package udesc.traffic.simulator.view;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import udesc.traffic.simulator.model.Carro;

/**
 *
 * @author davib
 */
public class Malha extends javax.swing.JFrame {

    private final List<Carro> carros;
    private int[][] malha = null;

    /**
     * Creates new form Malha
     */
    public Malha() {
        this.malha = new int[1][];
        this.carros = new ArrayList<>();
        initComponents();
    }

    private int[][] buscaDimensaoMalha() throws IOException {
        int linhas = 0;
        int colunas = 0;

        try {
            File file = new File("malha-exemplo-1.txt");
            BufferedReader br = new BufferedReader(new FileReader(file));

            for (int i = 0; i < 2; i++) {
                if (i == 0) {
                    linhas = Integer.parseInt(br.readLine().trim());
                }
                if (i == 1) {
                    colunas = Integer.parseInt(br.readLine().trim());
                }
            }
        } catch (IOException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Chegar "
                    + "arquivo de malha!");
        }
        return new int[linhas][colunas];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldQtdCarros = new javax.swing.JTextField();
        buttonIniciar = new javax.swing.JButton();
        buttonEncerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textFieldQtdCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldQtdCarrosActionPerformed(evt);
            }
        });

        buttonIniciar.setText("Iniciar");
        buttonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIniciarActionPerformed(evt);
            }
        });

        buttonEncerrar.setText("Encerrar");
        buttonEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEncerrarActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setLabelFor(textFieldQtdCarros);
        jLabel1.setText("QTD. MAX. VEÍCULOS");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldQtdCarros, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonEncerrar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldQtdCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonIniciar)
                    .addComponent(buttonEncerrar)
                    .addComponent(jLabel1))
                .addContainerGap(271, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldQtdCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldQtdCarrosActionPerformed

    }//GEN-LAST:event_textFieldQtdCarrosActionPerformed

    private void buttonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIniciarActionPerformed
        try {
            Integer qtdMaxCarros = Integer.valueOf(textFieldQtdCarros.getText().trim());

            for (int i = 0; i < qtdMaxCarros; i++) {
                Carro carro = new Carro();
                carros.add(carro);
                carro.start();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Insira um "
                    + "valor válido para a quantidade máxima de carros.");
        }
    }//GEN-LAST:event_buttonIniciarActionPerformed

    private void buttonEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEncerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEncerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Malha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Malha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Malha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Malha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Malha().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEncerrar;
    private javax.swing.JButton buttonIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textFieldQtdCarros;
    // End of variables declaration//GEN-END:variables
}
